version: "3.4"
services:

  # pipes
  in_pipe:
    build: ./pipes
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - PORT_A=${IN_PIPE_PORT_A}
      - PORT_B=${IN_PIPE_PORT_B}
  worker_pipe:
    build: ./pipes
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - PORT_A=${WORKER_PIPE_PORT_A}
      - PORT_B=${WORKER_PIPE_PORT_B}
  broker_pipe:
    build: ./pipes
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - PORT_A=${BROKER_PIPE_PORT_A}
      - PORT_B=${BROKER_PIPE_PORT_B}
      - BROADCAST_PORT=${BROKER_BROADCAST_PORT}

  broker:
    build: ./broker
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - BROKER_BROADCAST_PORT
      - BROKER_PIPE_HOST
      - BROKER_PIPE_IN_PORT=${BROKER_PIPE_PORT_B}
      - IN_PIPE_HOST
      - IN_PIPE_PORT=${IN_PIPE_PORT_B}
      - LOG_LEVEL
      - WORKER_PIPE_HOST
      - WORKER_PIPE_PORT=${WORKER_PIPE_PORT_A}

  test_worker:
    build: ./test_worker
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - LOG_LEVEL
