version: "3.4"
services:

  # pipes
  in_pipe:
    image: tengelisconsulting/pipes_py
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - LOG_LEVEL
      - IN_PORT=${IN_PIPE_PORT_A}
      - DEALER_PORT=${IN_PIPE_PORT_B}
  worker_pipe:
    image: tengelisconsulting/pipes_py
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - LOG_LEVEL
      - IN_PORT=${WORKER_PIPE_PORT_A}
      - DEALER_PORT=${WORKER_PIPE_PORT_B}
  broker_pipe:
    image: tengelisconsulting/pipes_py
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - LOG_LEVEL
      - IN_PORT=${BROKER_PIPE_PORT_A}
      - BROADCAST_PORT=${BROKER_BROADCAST_PORT}

  broker:
    image: tengelisconsulting/broker_py
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - BROKER_BROADCAST_PORT
      - BROKER_PIPE_HOST
      - BROKER_PIPE_IN_PORT=${BROKER_PIPE_PORT_A}
      - IN_PIPE_HOST
      - IN_PIPE_PORT=${IN_PIPE_PORT_B}
      - LOG_LEVEL
      - WORKER_PIPE_HOST
      - WORKER_PIPE_PORT=${WORKER_PIPE_PORT_B}

  # test_worker:
  #   build: ./test_worker
  #   network_mode: "host"
  #   restart: "unless-stopped"
  #   environment:
  #     - LOG_LEVEL
  #     - PORT=${WORKER_PIPE_PORT_A}
