#!/bin/bash

FILE=${BASH_SOURCE[0]:-${(%):-%x}}
HOOK_DIR="$( cd "$( dirname "${FILE}" )" >/dev/null 2>&1 && pwd )"
source ${HOOK_DIR}/hooks.env

set -e
if [[ "${IS_DOCKER_HUB}" == "1" ]]; then
    docker_hub_build pipes_py pipes
    docker_hub_build broker_py broker
else
    local_build pipes_py pipes
    local_build broker_py broker
fi


do_build() {
    image_name="${1}"
    build_dir="${2}"
    full_image_name=tengelisconsulting/${image_name}:${TAG}
    docker build -t ${full_image_name} ./${build_dir} \
        && docker push ${full_image_name} \
        && docker tag ${full_image_name} tengelisconsulting/${image_name}:latest \
        && docker push tengelisconsulting/${image_name}:latest
}

do_build pipes_py pipes \
&& do_build broker_py broker

# to make dockerhub happy
docker build -t tengelisconsulting/ez_arch:latest .
